### ISSUE TITLE
uuid identifier-column in mysql

### ISSUE THREAD

**Issue by cancabron** [DawnFire-Realms/CommunityBridge#224]
Ive a MyBB forum linked with CommunityBridge. Im using the linking-method: uuid

When a player register in the forum the uuid is written in the database, but i insert in this format:

069a79f444e94726a5befca90e38aaf5

And your plugin needs the "-" format, ej:

069a79f4-44e9-4726-a5be-fca90e38aaf5

Will you change this? Its only a question for change or not the php code.

Thanks and sorry for my english!

**Comment by TEKAA92** [comment]
@cancabron 
Just to be clear, you database saves the UUID in this format: `069a79f444e94726a5befca90e38aaf5 ` and CB looks for an UUID in this format: `069a79f4-44e9-4726-a5be-fca90e38aaf5`?

I just want to get rid of any uncertainty before getting to work :)

**Comment by cancabron** [comment]
Yeah, I supose it. Now we have coded to insert the uuid in this format aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee in the database. Example:

http://i.gyazo.com/12f135fd564debe6dd2a44c1d37394d8.png

Now i ve other problem. Is with the banning method.

Im using myBB forums. Should I open another issue?

**Comment by TEKAA92** [comment]
Open another issue if it is not related to this, and close this issue if it is not an issue anymore.

**Comment by cancabron** [comment]
Ok! Thanks!
