### ISSUE TITLE
Xenforo Syncs incompletely

### ISSUE THREAD

**Issue by nick-perry14** [DawnFire-Realms/CommunityBridge#257]
When syncing from xenforo -> server, it works perfectly.

When syncing groups from server -> xenforo, the usergroup DOES get changed, however the custom title set for that group does not.  How would this get fixed

(PEX permissions)

**Comment by ghost** [comment]
I don't believe these are related. Community Bridge simply sync's ranks, not titles. If that rank has a title.. and that use has that rank on your board...

**Comment by nick-perry14** [comment]
Well, I figured it out.  Xenforo has a seperate column (in the SQL Database) under users that is marked "User_display_group".

Community bridge only changes the group, but doesnt sync the display group with the newly assigned group, as it typically does when you manually change a users group
