### ISSUE TITLE
"Insert" Problem

### ISSUE THREAD

**Issue by PrawnCocktail** [DawnFire-Realms/CommunityBridge#95]
Hi, May i just say this plugin is fantastic and well worth the time its taken to setup. Unfortunately i have had one major issue that i just cannot figure out.  Just after the Statistics section in the config.yml there is a section called "insert:". I am using xenforo and used another users question to set statistics up. and i used the config suggested in that post for the insert section. It said that the config should look like this:

  insert:
    enabled: false
    method: generic
    theme-id-column: 
    theme-id:

With this config setting,everything works as it should regarding custom profile fields, but only if they already have a value in the field. If there is no value, then it wont show up in the database and therefore cant be changed. From what i understand, the point in the theme-id columns is to put a default value in the custom field, is that correct?  If so, what is the correct database info for those 2 options? I have looked around and cant see anything like theme-id in the database, but nor can i find people with the same issue as me, which might suggest there is a way around it? I have tried to see if i can set a default value via xenforo but that's not possible from what Ive read. 

Any help would be great.

Chris.

**Comment by axepex** [comment]
A great question! What a shame you skimped on the answer. There is no documentation on this section!
